services:
  postgres:
    image: postgres:15
    container_name: octyra_postgres
    environment:
      POSTGRES_USER: octyra_user
      POSTGRES_PASSWORD: octyra_pass
      POSTGRES_DB: octyra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: octyra_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: octyra_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    container_name: octyra_worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=solo

  celery_beat:
    build: .
    container_name: octyra_beat
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: celery -A app.workers.celery_app beat --loglevel=info

volumes:
  postgres_data: